services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATA_FOLDER}/postgres:/var/lib/postgresql/data
    networks:
      - homeassistant_network

  influxdb:
    container_name: influxdb
    image: influxdb:1.11.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_USER_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      TZ: ${TZ}      
    volumes:
      - ${DATA_FOLDER}/influxdb/data:/var/lib/influxdb
      - ${DATA_FOLDER}/influxdb/config/:/etc/influxdb2
    networks:
      - homeassistant_network
      

  # grafana:
  #   restart: unless-stopped
  #   depends_on:
  #     - influxdb
  #   image: grafana/grafana:main-ubuntu
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
  #   volumes:
  #     - ${DATA_FOLDER}/grafana:/var/lib/grafana
  #   networks:
  #     - homeassistant_network
      

  homeassistant:
    depends_on:
      - postgres
      - influxdb
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    privileged: true
    environment:
    # TODO: vedere se serve
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/homeassistant 
      - TZ=${TZ}
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    volumes:
      - ${DATA_FOLDER}/home-assistant:/config
    ports:
      - "8123:8123"
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyACM0
    networks:
      - homeassistant_network

  # letsencrypt:
  #   container_name: lets-encrypt
  #   image: linuxserver/letsencrypt:version-1.11.0
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - ${DATA_FOLDER}/letsencrypt/config:/config
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - PGID=1000
  #     - PUID=1000
  #     - EMAIL={email}
  #     - URL={url}
  #     - SUBDOMAINS=hass
  #     - VALIDATION=http
  #   networks:
  #     - homeassistant_network

  nodered:
    container_name: nodered
    image: nodered-home-assistant
    volumes:
      - ${DATA_FOLDER}/nodered/:/data
    ports:
      - "1880:1880"
    user: 'root'
    environment:
      - TZ=${TZ}
    networks:
      - homeassistant_network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

networks:
  homeassistant_network:
    driver: bridge
