
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: homeassistant
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - homeassistant_network

  influxdb:
    container_name: influxdb
    image: influxdb:1.11.7
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - homeassistant_network

  grafana:
    restart: unless-stopped
    depends_on:
      - influxdb
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - homeassistant_network
      

  homeassistant:
    depends_on:
      - postgres
      - influxdb
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    privileged: true
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/homeassistant
      - TZ=${TZ}
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    volumes:
      - ./data/homeassistant:/config
    ports:
      - "8123:8123"
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
      - /dev/ttyACM0
    networks:
      - homeassistant_network

  letsencrypt:
    container_name: lets-encrypt
    image: linuxserver/letsencrypt:version-1.11.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/letsencrypt/config:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL={email}
      - URL={url}
      - SUBDOMAINS=hass
      - VALIDATION=http
    networks:
      - homeassistant_network

  nodered:
    container_name: nodered
    image: nodered-home-assistant
    volumes:
      - ./data/nodered/:/data
    ports:
      - "1880:1880"
    user: 'root'
    environment:
      - TZ=${TZ}
    networks:
      - homeassistant_network

networks:
  homeassistant_network:
    driver: bridge
