
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Database
recorder:
  db_url: !secret psql_string
  db_retry_wait: 3
  # exclude:
  #   domains:
  #     - automation
  #     - updater
  #   entity_globs:
  #     - sensor.weather_*
  #   entities:
  #     - sun.sun 
  #     - sensor.last_boot
  #     - sensor.date
  #   event_types:
  #     - call_service

history:

influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: 8086
  token: !secret influxdb_token
  organization: !secret influx_org
  bucket: homeassistant
  tags:
    source: HomeAssistant
  tags_attributes:
    - friendly_name
  default_measurement: units
  ignore_attributes:
    - icon
  # exclude:
  #   entities:
  #     - zone.home
  #   domains:
  #     - persistent_notification
  #     - person